### ISSUE TITLE
Ribbits trying to stop playing song causes a crash

### ISSUE THREAD

**Issue by Jous4n** [yungnickyoung/Ribbits#13] opened 2024-07-27 06:23 UTC
https://mclo.gs/I1n1HSo

**Comment by yungnickyoung** [comment] 2024-11-04 03:40
Duplicate of #3 . I just added a null check that should at the very least prevent the game from crashing. That fix will be included in the next release, v3.0.1. Will hopefully be out in a week or so. If the problem persists at that point, please open a new issue report.

**Closed as completed by yungnickyoung** 2024-11-04 03:40 UTC
Labels: duplicate
